# 1 -topshiriq

numbers = (10, 2, 3, 4, 5, 6)
print("any: ")
print(any(numbers))
print("max: ")
print(max(numbers))
print("min: ")
print(min(numbers))
print("len: ")
print(len(numbers))
print("sorted: ")
print(sorted(numbers))
print("sum: ")
print(sum(numbers))
